### ISSUE TITLE
Possibility to disturb the measurements

### ISSUE THREAD

**Issue by marek22k** [benjojo/sping#18]
It is possible for an attacker to send UDP packets with any session ID. By sending 2**32 packets with a session ID starting at 0, the attacker would manage to falsify all active measurements by one value.
One way to prevent this is to allow an IP address only a limited number of "failed attempts" (i.e. packets with a session ID that cannot be associated) and then block it for a period of time.

**Comment by benjojo** [comment]
Sending 2^31 packets (or at a bare min 137GB) to disrupt a sping measurement is not a practical attack for the "reward" you get at the end
