### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by tamihiro** [benjojo/sping#8]
Hi, thanks for sharing the code. I often get a runtime error after running sping for sometime. Please check the output in [this link](https://github.com/benjojo/sping/files/6099816/sping.log). 
I have PR'ed #7 which I think should be a fix for this problem, treating timeSyncs as a struct with sync.Mutex as its member field. With this fix I have been running it for several hours now.

**Comment by benjojo** [comment]
Looks like the NTP calibration is a little broken. I'll take a look

**Comment by benjojo** [comment]
Merged your PR, thanks
